import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  video: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#000',
  },
  tapLayer: {
    ...StyleSheet.absoluteFill,
    zIndex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'space-between',
    zIndex: 2,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? 12 : 44,
    paddingBottom: 20,
    paddingHorizontal: 12,
  },
  backBtn: { marginRight: 8 },
  title: {
    flex: 1,
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Poppins-SemiBold',
    marginHorizontal: 8,
  },
  centerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 32,
  },
  seekBtn: { opacity: 0.9 },
  playPauseBtn: { opacity: 0.95 },
  bottomBar: {
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'android' ? 20 : 32,
    paddingTop: 24,
  },
  progressTouch: {
    height: 28,
    justifyContent: 'center',
    marginBottom: 4,
  },
  track: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.3)',
    overflow: 'visible',
  },
  played: {
    height: '100%',
    borderRadius: 2,
    overflow: 'hidden',
  },
  thumb: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#fff',
    top: -5,
    marginLeft: -7,
  },
  timeText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
  errorOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.85)',
    zIndex: 3,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  errText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  errPath: {
    color: Colors.textMuted,
    fontSize: 11,
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 8,
    paddingHorizontal: 24,
    paddingVertical: 10,
    backgroundColor: Colors.accent1,
    borderRadius: 12,
  },
  retryText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
  },
  subtitleOverlay: {
    position: 'absolute',
    bottom: 96,
    left: 20,
    right: 20,
    alignItems: 'center',
    zIndex: 20,
  },
  subtitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  subtitleWord: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
  },
  dictCard: {
    position: 'absolute',
    top: 80,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(15,15,26,0.9)',
    borderWidth: 1,
    borderColor: Colors.glassBorder,
    borderRadius: 16,
    padding: 12,
    zIndex: 50,
  },
  dictHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    paddingBottom: 6,
    marginBottom: 6,
  },
  dictTitle: {
    color: Colors.accent2,
    fontSize: 16,
    fontFamily: 'Poppins-Bold',
  },
  dictText: {
    color: '#E2E8F0',
    fontSize: 13,
    lineHeight: 18,
  },
  dictFooter: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 8 },
  resumeBtn: { paddingHorizontal: 12, paddingVertical: 6, backgroundColor: Colors.accent1, borderRadius: 8 },
  resumeBtnText: { color: '#fff', fontSize: 12, fontFamily: 'Poppins-Bold' },
  topRightRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  bookmarkTick: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.danger,
    marginLeft: -3,
    top: -1,
  },
  bottomControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  bottomRightControls: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  rateText: { color: '#fff', fontSize: 13, fontFamily: 'Poppins-Bold' },
  sheetContainer: { flex: 1, padding: 16 },
  emptySheetContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
  },
  emptySheetText: { color: Colors.textMuted, marginTop: 8, fontSize: 14 },
  emptySheetDesc: { color: Colors.textMuted, marginTop: 4, fontSize: 12, textAlign: 'center' },
  bookmarkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: Colors.glassBorder,
  },
  bookmarkPressable: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  bookmarkIcon: { marginRight: 12 },
  bookmarkText: { color: '#fff', fontSize: 15, fontFamily: 'Poppins-SemiBold' },
  sideSlidersContainer: {
    position: 'absolute',
    top: 100,
    bottom: 100,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 10,
    pointerEvents: 'none',
  },
  verticalSlider: {
    width: 36,
    height: 160,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    pointerEvents: 'auto',
  },
  sliderTrack: {
    width: 4,
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 2,
    marginVertical: 6,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  sliderFill: {
    width: '100%',
    borderRadius: 2,
  },
  sliderValueText: {
    color: '#fff',
    fontSize: 9,
    fontFamily: 'Poppins-ExtraBold',
    marginTop: 2,
  },
  audioTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: Colors.glassBorder,
  },
  audioTrackPressable: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  audioTrackIcon: {
    marginRight: 12,
  },
  audioTrackText: {
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Poppins-SemiBold',
  },
  activeAudioTrackText: {
    color: Colors.accent2,
  },
});

