import { StyleSheet } from 'react-native';
import { Colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  centerAbsolute: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
  },
  left: { flex: 1 },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  iconBtn: { padding: 6 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    padding: 10,
    borderRadius: 14,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.glassBorder,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: Colors.textPrimary,
    fontSize: 14,
    paddingVertical: 0,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  statsText: {
    color: Colors.textMuted,
    fontSize: 12,
    fontFamily: 'Poppins-SemiBold',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  listContent: { paddingHorizontal: 12, paddingTop: 4 },
  cardWrapper: { flex: 1, marginHorizontal: 6, marginVertical: 0 },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 80,
    gap: 12,
  },
  emptyText: { color: Colors.textSecondary, fontSize: 16, fontFamily: 'Poppins-SemiBold' },
  emptyBtn: {
    marginTop: 8,
    backgroundColor: Colors.accent1,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  emptyBtnText: { color: '#fff', fontFamily: 'Poppins-Bold', fontSize: 14 },
  // Continue Watching section
  continueSection: { paddingTop: 0, paddingBottom: 16 },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 6,
  },
  sectionTitle: {
    color: Colors.textPrimary,
    fontSize: 15,
    fontFamily: 'Poppins-SemiBold',
  },
  continueListContent: { paddingHorizontal: 16, gap: 12 },
  continueCard: {
    width: 200,
    marginRight: 12,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: Colors.surface,
  },
  continueThumbWrap: {
    width: 200,
    height: 112,
    backgroundColor: '#0d0d1f',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  continueThumb: { width: '100%', height: '100%' },
  continueProgressBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  continueProgressFill: {
    height: '100%',
    backgroundColor: Colors.accent1,
  },
  continueRemainingPill: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  continueRemainingText: {
    color: '#fff',
    fontSize: 10,
    fontFamily: 'Poppins-SemiBold',
  },
  continueInfo: { paddingHorizontal: 10, paddingVertical: 8 },
  continueTitle: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontFamily: 'Poppins-SemiBold',
  },
  continueSubtitle: {
    color: Colors.textMuted,
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
  },
  clearBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    padding: 4,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
  },
  // View toggle row (replaces statsRow)
  viewToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 6,
    gap: 4,
  },
  viewToggleBtn: {
    padding: 8,
    borderRadius: 10,
  },
  // Folder list-row
  folderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginHorizontal: 4,
    marginVertical: 4,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    gap: 12,
  },
  folderRowThumb: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: Colors.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  folderRowInnerIcon: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  folderRowMeta: { flex: 1 },
  folderRowName: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  folderRowSub: {
    color: Colors.textMuted,
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
  },
});

